
project_id = "pxwnldtwtbiwjlnwzlvt"

[auth]
disable_signup = false
enable_email_signup = true
enable_email_autoconfirm = true
site_url = "http://localhost:5173"
additional_redirect_urls = ["http://localhost:5173", "http://localhost:5173/dashboard"]
