// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pxwnldtwtbiwjlnwzlvt.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InB4d25sZHR3dGJpd2psbnd6bHZ0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDA5NDY0MzcsImV4cCI6MjA1NjUyMjQzN30.QoTBPYAnQCRajwp3TeIETNISyACveukaQyVQd60CHWQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);